# Generated by Django 3.1.7 on 2021-03-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
    ]
