# Generated by Django 3.1.7 on 2021-03-29 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=50)),
                ('start_station', models.CharField(max_length=50)),
                ('end_station', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('train_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=50)),
                ('route_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.route')),
            ],
        ),
    ]
