# Generated by Django 3.1.7 on 2021-03-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trains',
            new_name='Train',
        ),
    ]
