# Generated by Django 3.1.7 on 2021-03-29 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_routestation_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessanger_record', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_date', models.CharField(max_length=50)),
                ('cancel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('booking_no', models.IntegerField()),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('train_classes', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pessanger_record', models.CharField(max_length=50)),
                ('start_station', models.CharField(max_length=50)),
                ('end_station', models.CharField(max_length=50)),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.train')),
            ],
        ),
    ]
