# Generated by Django 3.1.7 on 2021-03-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210329_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
