# Generated by Django 3.1.7 on 2021-04-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210402_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='train_classes',
            new_name='classes',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='booking_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='booking_no',
            new_name='reserve_no',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='route_no',
            new_name='route_id',
        ),
        migrations.RemoveField(
            model_name='routestation',
            name='departure_time',
        ),
    ]
