# Generated by Django 3.1.7 on 2021-04-02 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210402_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='train_no',
            new_name='train',
        ),
        migrations.RenameField(
            model_name='routestation',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='routestation',
            old_name='station_id',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='routestation',
            old_name='train_no',
            new_name='train',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='station_id',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='route_id',
            new_name='route',
        ),
    ]
