# Generated by Django 3.1.7 on 2021-04-02 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210402_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routestation',
            old_name='train',
            new_name='train_no',
        ),
    ]
