# Generated by Django 3.1.7 on 2021-04-02 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210402_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='train',
            new_name='train_no',
        ),
    ]
