# Generated by Django 3.1.7 on 2021-04-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210402_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='train_no',
            new_name='train',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='e_station',
            new_name='end_station',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='s_station',
            new_name='start_station',
        ),
        migrations.RenameField(
            model_name='routestation',
            old_name='train_no',
            new_name='train',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='station',
            new_name='station_id',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='train_no',
            new_name='train_id',
        ),
        migrations.AddField(
            model_name='routestation',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
