# Generated by Django 3.1.7 on 2021-04-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210402_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestation',
            options={'ordering': ['order']},
        ),
    ]
