# Generated by Django 3.1.7 on 2021-04-02 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210402_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestation',
            options={},
        ),
    ]
