# Generated by Django 3.1.7 on 2021-04-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210402_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='journey_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='classes',
            new_name='no_of_seats',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pessanger_record',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reserve_no',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_no',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
