# Generated by Django 3.1.7 on 2021-04-02 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210402_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_no',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
