# Generated by Django 3.1.7 on 2021-04-06 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210402_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
